# Exported from Render on 2025-11-27T15:25:13Z
version: "1"
services:
- type: web
  name: n8n
  runtime: docker
  repo: https://github.com/dilshu/my-n8n
  plan: free
  envVars:
  - key: WEBHOOK_URL
    sync: false
  - key: N8N_PORT
    sync: false
  - key: N8N_BASIC_AUTH_PASSWORD
    sync: false
  - key: N8N_BASIC_AUTH_USER
    sync: false
  - key: N8N_BASIC_AUTH_ACTIVE
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
